#!/usr/bin/env bash
#
# Git Post-Commit Hook — Auto-update SNAPSHOT.md
# Executed after every git commit
#
# Installation:
#   cp .git/hooks/post-commit .git/hooks/post-commit.local
#   chmod +x .git/hooks/post-commit.local
#

set -euo pipefail

# Get project root (hook runs in .git/hooks/)
PROJECT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo ".")"
cd "$PROJECT_ROOT"

# Skip if .qwen/SNAPSHOT.md doesn't exist
if [[ ! -f ".qwen/SNAPSHOT.md" ]]; then
    exit 0
fi

# Get current date
DATE=$(date +"%Y-%m-%d %H:%M")

# Get git info
LATEST_COMMIT=$(git log -1 --oneline 2>/dev/null || echo "no commits")
COMMIT_COUNT=$(git rev-list --count HEAD 2>/dev/null || echo "0")
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")

# Get commit message
COMMIT_MSG=$(git log -1 --pretty=%s 2>/dev/null || echo "unknown")

# Update SNAPSHOT.md
cat > .qwen/SNAPSHOT.md << EOF
# Project State Snapshot

**Project:** $(basename "$PWD")  
**Last Updated:** $DATE  
**Version:** v1.0.0

---

## Current Status

Auto-updated after commit: $COMMIT_MSG

## Recent Git Activity

**Branch:** $BRANCH  
**Latest commit:** $LATEST_COMMIT  
**Total commits:** $COMMIT_COUNT  
**Last commit time:** $(date -r "$(git log -1 --format=%ct 2>/dev/null || echo "now")" +"%Y-%m-%d %H:%M" 2>/dev/null || echo "unknown")

## Project Health

**Status:** ✅ Active development  
**Last activity:** $DATE

---

*This file is auto-generated by git post-commit hook. Do not commit to version control.*
EOF

echo "[post-commit] SNAPSHOT.md updated: $COMMIT_MSG"

exit 0
