#
# Git Post-Commit Hook — Auto-update SNAPSHOT.md
# Executed after every git commit (PowerShell version)
#
# Installation:
#   Copy to .git/hooks/post-commit.ps1
#   Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
#

# Get project root (hook runs in .git/hooks/)
try {
    $ProjectRoot = git rev-parse --show-toplevel 2>$null
    if ($ProjectRoot) { Set-Location $ProjectRoot }
} catch {
    $ProjectRoot = "."
}

# Skip if .qwen/SNAPSHOT.md doesn't exist
if (-not (Test-Path ".qwen\SNAPSHOT.md")) {
    exit 0
}

# Get current date
$Date = Get-Date -Format "yyyy-MM-dd HH:mm"

# Get git info
try {
    $LatestCommit = git log -1 --oneline 2>$null
    if (-not $LatestCommit) { $LatestCommit = "no commits" }
    $CommitCount = git rev-list --count HEAD 2>$null
    if (-not $CommitCount) { $CommitCount = "0" }
    $Branch = git branch --show-current 2>$null
    if (-not $Branch) { $Branch = "unknown" }
    $CommitMsg = git log -1 --pretty=%s 2>$null
    if (-not $CommitMsg) { $CommitMsg = "unknown" }
    $CommitTimeEpoch = git log -1 --format=%ct 2>$null
    if ($CommitTimeEpoch) {
        $CommitTime = [DateTimeOffset]::FromUnixTimeSeconds($CommitTimeEpoch).Local.ToString("yyyy-MM-dd HH:mm")
    } else {
        $CommitTime = "unknown"
    }
} catch {
    $LatestCommit = "git error"
    $CommitCount = "0"
    $Branch = "unknown"
    $CommitMsg = "unknown"
    $CommitTime = "unknown"
}

# Update SNAPSHOT.md
$SnapshotContent = @"
# Project State Snapshot

**Project:** $(Split-Path -Path $PWD -Leaf)  
**Last Updated:** $Date  
**Version:** v1.0.0

---

## Current Status

Auto-updated after commit: $CommitMsg

## Recent Git Activity

**Branch:** $Branch  
**Latest commit:** $LatestCommit  
**Total commits:** $CommitCount  
**Last commit time:** $CommitTime

## Project Health

**Status:** ✅ Active development  
**Last activity:** $Date

---

*This file is auto-generated by git post-commit hook. Do not commit to version control.*
"@

Set-Content -Path ".qwen\SNAPSHOT.md" -Value $SnapshotContent -Encoding UTF8

Write-Host "[post-commit] SNAPSHOT.md updated: $CommitMsg"

exit 0
